Repository planetarium/planet-clicker, pull requests merged in 2022-05, with the labels that each got.

#39 Fix unity version typo
  EXAMPLE.md
Labels: Extra Small

#43 Bump libplanet to 0.35.0
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Net.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Net.xml
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Net.xml.meta
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.RocksDBStore.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Stun.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.xml
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.xml.meta
Labels: Extra Large

#44 Bump libplanet to 0.36.1
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Net.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Net.xml
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.RocksDBStore.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Stun.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.xml
Labels: Large

#45 ⬆️ Bump libplanet
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.dll.meta
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.xml
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.xml.meta
Labels: Large

#47 Store `PrivateKey` as file
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Editor/LibplanetEditor.cs
  planet-clicker/Assets/LibplanetUnity/Helper/Options.cs
Labels: Medium

#48 New genesis block
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/StreamingAssets/genesis
Labels: Extra Small

#49 Bump libplanet-node; add config generation to editor
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Editor/LibplanetEditor.cs
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.xml
Labels: Large

#50 Chore/refactor
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Helper/Options.cs
Labels: Small

#51 ⬆️ Bump libplanet libplanet-node branch
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Net.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Net.xml
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Stun.dll
Labels: Medium
