Repository planetarium/planet-clicker, pull requests merged in 2022-06, with the labels that each got.

#52 Bump libplanet's `libplanet-node` branch
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Editor/LibplanetEditor.cs
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.xml
Labels: Large

#55 ⬆️ Bump libplanet to 0.38.0
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Net.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.xml
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.RocksDBStore.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Stun.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.xml
Labels: Extra Small

#56 🔀 Libplanet node
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Editor/LibplanetEditor.cs
  planet-clicker/Assets/LibplanetUnity/Helper/Options.cs
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Net.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Net.xml
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.dll.meta
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.xml
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Node.xml.meta
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.RocksDBStore.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Stun.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.xml
  planet-clicker/Assets/StreamingAssets/genesis
Labels: Extra Large

#57 Apply Miner
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.dll.meta
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.xml
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.xml.meta
Labels: Large

#58 ♻️ Remove path dependency from `Agent`
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Editor/LibplanetEditor.cs
  planet-clicker/Assets/LibplanetUnity/Paths.cs
  planet-clicker/Assets/LibplanetUnity/Paths.cs.meta
Labels: Medium

#59 ⚰️ CLI options removed
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Helper/Options.cs
  planet-clicker/Assets/LibplanetUnity/Helper/Options.cs.meta
Labels: Small

#61 ♻️ Use `Libplanet.Unity` `ActionBase`
  planet-clicker/Assets/LibplanetUnity/Action/AccountStateDeltaExtensions.cs
  planet-clicker/Assets/LibplanetUnity/Action/AccountStateDeltaExtensions.cs.meta
  planet-clicker/Assets/LibplanetUnity/Action/ActionBase.cs
  planet-clicker/Assets/LibplanetUnity/Action/ActionBase.cs.meta
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.xml
  planet-clicker/Assets/_Script/Action/AddCount.cs
  planet-clicker/Assets/_Script/Action/SubCount.cs
  planet-clicker/Assets/_Script/Game.cs
Labels: Small

#62 Cleanup artifacts
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/_Script/Action/AddCount.cs
Labels: Extra Small

#63 ♻️ Attempt to decouple via higher granularity
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Editor/LibplanetEditor.cs
  planet-clicker/Assets/LibplanetUnity/InitHelper.cs
  planet-clicker/Assets/LibplanetUnity/InitHelper.cs.meta
  planet-clicker/Assets/LibplanetUnity/Utils.cs
  planet-clicker/Assets/LibplanetUnity/Utils.cs.meta
  planet-clicker/Assets/StreamingAssets/swarm_config.json
  planet-clicker/Assets/StreamingAssets/swarm_config.json.meta
Labels: Medium

#60 Refactor agent
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/DefaultMineHandler.cs
  planet-clicker/Assets/LibplanetUnity/DefaultMineHandler.cs.meta
  planet-clicker/Assets/LibplanetUnity/MonoSingleton.cs
  planet-clicker/Assets/LibplanetUnity/SwarmRunner.cs
  planet-clicker/Assets/LibplanetUnity/SwarmRunner.cs.meta
  planet-clicker/Assets/_Script/Game.cs
Labels: Large

#64 ♻️ `IAction` type consistency
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/DefaultMineHandler.cs
  planet-clicker/Assets/_Script/Game.cs
Labels: Extra Small

#65 ♻️ `Paths` and `Utils` moved to `Libplanet.Unity`
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Editor/LibplanetEditor.cs
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.xml
  planet-clicker/Assets/LibplanetUnity/Paths.cs
  planet-clicker/Assets/LibplanetUnity/Paths.cs.meta
  planet-clicker/Assets/LibplanetUnity/Utils.cs
  planet-clicker/Assets/LibplanetUnity/Utils.cs.meta
Labels: Medium

#66 Update miner
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/DefaultMineHandler.cs
  planet-clicker/Assets/LibplanetUnity/DefaultMineHandler.cs.meta
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.xml
Labels: Medium

#67 ⬆️ Bump libplanet-unity
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/InitHelper.cs
  planet-clicker/Assets/LibplanetUnity/InitHelper.cs.meta
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.xml
Labels: Medium

#68 Bump libplanet unity
  planet-clicker/Assets/LibplanetUnity/Agent.cs
  planet-clicker/Assets/LibplanetUnity/Agent.cs.meta
  planet-clicker/Assets/LibplanetUnity/MonoSingleton.cs
  planet-clicker/Assets/LibplanetUnity/MonoSingleton.cs.meta
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.xml
  planet-clicker/Assets/LibplanetUnity/SwarmRunner.cs
  planet-clicker/Assets/LibplanetUnity/SwarmRunner.cs.meta
  planet-clicker/Assets/_Script/Action/AddCount.cs
  planet-clicker/Assets/_Script/Action/SubCount.cs
  planet-clicker/Assets/_Script/Game.cs
Labels: Large

#69 QoL quick access to various locations
  planet-clicker/Assets/LibplanetUnity/Editor/Locations.cs
  planet-clicker/Assets/LibplanetUnity/Editor/Locations.cs.meta
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.dll
  planet-clicker/Assets/LibplanetUnity/Packages/Libplanet.Unity.xml
Labels: Small

#71 Temp private keys feature
  planet-clicker/Assets/Libplanet.Unity/Editor/BlockChainMenu.cs
  planet-clicker/Assets/Libplanet.Unity/Editor/GenesisBlockMenu.cs
  planet-clicker/Assets/Libplanet.Unity/Editor/PrivateKeyMenu.cs
  planet-clicker/Assets/Libplanet.Unity/Editor/SwarmConfigMenu.cs
Labels: Small

#72 Refactor State & DataModel
  planet-clicker/Assets/Prefabs/Button.prefab
  planet-clicker/Assets/Prefabs/Button.prefab.meta
  planet-clicker/Assets/Scenes/Game.unity
  planet-clicker/Assets/_Script/Action/AddCount.cs
  planet-clicker/Assets/_Script/Data/CountData.cs
  planet-clicker/Assets/_Script/Game.cs
  planet-clicker/Assets/_Script/State/CountState.cs
Labels: Extra Large

#74 `DataModel` implementation
  planet-clicker/Assets/_Script/Action/AddCount.cs
  planet-clicker/Assets/_Script/Action/AddCountPlainValue.cs
  planet-clicker/Assets/_Script/Action/AddCountPlainValue.cs.meta
  planet-clicker/Assets/_Script/Action/SubCount.cs
  planet-clicker/Assets/_Script/Action/SubCountPlainValue.cs
  planet-clicker/Assets/_Script/Action/SubCountPlainValue.cs.meta
  planet-clicker/Assets/_Script/Game.cs
  planet-clicker/Assets/_Script/State/CountState.cs
  planet-clicker/Assets/_Script/State/CountState.cs.meta
  planet-clicker/Assets/_Script/State/RankingState.cs
  planet-clicker/Assets/_Script/State/State.cs
  planet-clicker/Assets/_Script/State/State.cs.meta
Labels: Large

#75 ♻️ Refactor general
  planet-clicker/Assets/_Script/Click.cs
  planet-clicker/Assets/_Script/Data/IRow.cs
  planet-clicker/Assets/_Script/Data/IRow.cs.meta
  planet-clicker/Assets/_Script/Data/ITable.cs
  planet-clicker/Assets/_Script/Data/Level.cs
  planet-clicker/Assets/_Script/Data/Table.cs
  planet-clicker/Assets/_Script/Game.cs
Labels: Medium
